#ifndef ROOTKIT_PROTOCOL_H
#define ROOTKIT_PROTOCOL_H

#define R_OPER short

#define R_OPER_DISCONNECT ((R_OPER) 0)

#define R_OPER_EXEC_SHELL_COMMAND ((R_OPER) 1)
#define R_OPER_SHELL_COMAMND_SZ short
#define R_OPER_SHELL_COMAMND_OUTPUT_SZ int

#define R_OPER_EXEC_C_PROGRAM  ((R_OPER) 2)
#define R_OPER_C_PROGRAM_SZ int

#endif //ROOTKIT_PROTOCOL_H
